package stationary;

import java.sql.*;
import java.math.*;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Rafael_jz
 */
public class Interfaz extends javax.swing.JFrame {

    static Connection conn;
    static Statement sentencia;
    static ResultSet resultado;

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        nom_prod2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        results = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        busqueda = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        insertar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        nom_prod = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cant = new javax.swing.JTextField();
        precio = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        id_registro = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cant_registro = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        registrar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        jLabel6.setText("Cantidad del producto:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        results.setColumns(20);
        results.setRows(5);
        jScrollPane1.setViewportView(results);

        jLabel1.setText("BUSCADOR:");

        busqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busquedaActionPerformed(evt);
            }
        });

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("ID --- NOMBRE_PROD --- CANTIDAD --- PRECIO_UNIT");

        insertar.setText("Insertar producto");
        insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarActionPerformed(evt);
            }
        });

        jLabel3.setText("INSERCIONES:");

        jLabel4.setText("Nombre del producto:");

        jLabel5.setText("Cantidad del producto:");

        jLabel7.setText("Precio unitario:");

        jLabel8.setText("REGISTRO:");

        id_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_registroActionPerformed(evt);
            }
        });

        jLabel9.setText("ID del producto:");

        jLabel10.setText("Cantidad:");

        registrar.setText("Registrar");
        registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarActionPerformed(evt);
            }
        });

        jLabel11.setText("<-- presionar una sola vez !");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(busqueda)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton1))
                        .addComponent(insertar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(nom_prod)
                        .addComponent(jLabel5)
                        .addComponent(cant))
                    .addComponent(jLabel7)
                    .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(id_registro, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(cant_registro, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(registrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nom_prod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(insertar)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(id_registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cant_registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrar)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(98, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void busquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_busquedaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        results.setText(buscar(busqueda.getText()));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void insertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarActionPerformed

        if ((nom_prod.getText() != "") && (Integer.parseInt(precio.getText()) != 0)) {
            results.setText(insertar(nom_prod.getText(), Integer.parseInt(cant.getText()), Integer.parseInt(precio.getText())));
        } else {
            results.setText("Los datos ingresados son invalidos");
        }
        JOptionPane.showMessageDialog(null, "El producto: " + nom_prod.getText() + " ha sido insertado con exito","Alerta",JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_insertarActionPerformed

    private void registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarActionPerformed
        results.append(registrar(Integer.parseInt(id_registro.getText()), Integer.parseInt(cant_registro.getText())));
        JOptionPane.showMessageDialog(null, "El producto con id: " + id_registro.getText() + " ha sido registrado con exito","Alerta",JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_registrarActionPerformed

    private void id_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_registroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_registroActionPerformed

    public static String buscar(String st) {

        String salida = "";

        try {
            System.out.println("Buscando...");
            resultado = sentencia.executeQuery("SELECT * FROM stationery WHERE pr_name LIKE '%" + st + "%'");

            // Se recorren las tuplas retornadas
            while (resultado.next()) {
                salida = salida + "\n" + (resultado.getInt("id") + " --- " + resultado.getString("pr_name") + " --- " + resultado.getInt("inventory") + " --- " + resultado.getInt("unit_price"));
            }
        } catch (SQLException e) {
            System.out.println("Error: " + e.getMessage());
        }
        return salida;
    }

    public static int conteo() {

        int cont = 0;

        try {
            System.out.println("Contando...");
            resultado = sentencia.executeQuery("SELECT COUNT(*) AS count FROM stationery");

            if (resultado.next()) {
                cont = resultado.getInt("count");
            }
        } catch (SQLException e) {
            System.out.println("Error: " + e.getMessage());
        }
        return cont;
    }

    public static String insertar(String prod, int cant, int price) {

        int count = conteo() + 1;
        String salida = "No se pudo insertar";

        try {
            System.out.println("Insertando...");
            String sqlstmt = "INSERT INTO stationery VALUES (" + count + ",'" + prod + "'," + cant + "," + price + ")";
            sentencia.executeUpdate(sqlstmt);
            salida = "El producto: " + prod + " ha sido insertad@ con exito";
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        return salida;
    }

    public static String registrar(int ID_reg, int cant_reg) {

        int new_cant;
        int precio_reg;
        String SQLstmt;
        String prod = "";

        try {
            System.out.println("Buscando...");
            resultado = sentencia.executeQuery("SELECT * FROM stationery WHERE id = " + ID_reg);
            while(resultado.next()){
                prod = resultado.getString("pr_name");
            if (resultado.getInt("inventory") - cant_reg > 0) {
                new_cant = resultado.getInt("inventory") - cant_reg;
                precio_reg = cant_reg * resultado.getInt("unit_price");
                SQLstmt = "UPDATE stationery SET id = " + resultado.getInt("id") + ", pr_name = '" + prod + "', inventory = " + new_cant + ", unit_price = " + resultado.getInt("unit_price") + " WHERE id = " + ID_reg;
                sentencia.execute(SQLstmt);
                System.out.println("Producto registrado con exito");
            }else{
                System.out.println("No se puede registrar la compra pq el pedido supera las unidades en el inventario");
            }
            }
        } catch (SQLException e) {
            System.out.println("Error: " + e.getMessage());
        }
        return "El producto: " + prod + " ha sido registrado con exito\n";
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        System.out.println("Conectado a la base de datos de lapiz y papel...");

        try { // Se carga el driver JDBC-ODBC
            Class.forName("oracle.jdbc.driver.OracleDriver");
        } catch (Exception e) {
            System.out.println("No se pudo cargar el driver JDBC");
            return;
        }
        try { // Se establece la conexion con la base de datos
            conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "raejimenezca", "bases2018");
            sentencia = conn.createStatement();
        } catch (SQLException e) {
            System.out.println("No hay conexion con la base de datos");
            return;
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    } // FIN DEL MAIN

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField busqueda;
    private javax.swing.JTextField cant;
    private javax.swing.JTextField cant_registro;
    private javax.swing.JTextField id_registro;
    private javax.swing.JButton insertar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nom_prod;
    private javax.swing.JTextField nom_prod2;
    private javax.swing.JTextField precio;
    private javax.swing.JButton registrar;
    private javax.swing.JTextArea results;
    // End of variables declaration//GEN-END:variables
}
